# For more information, see:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-18.04'

jobs:
- job: 'Build_GCC'
  displayName: 'Release build of JitCat on Linux with GCC'
  steps:
    - task: CMake@1
      displayName: 'CMake'
      inputs:
        cmakeArgs: '..'

    - task: CMake@1
      displayName: 'CMake'
      inputs:
        cmakeArgs: '--build . --config Release -j2'
    - script: 'tree .'
      displayName: 'Directory structure'
      failOnStderr: false
      enabled: true  
    - publish: '$(Build.SourcesDirectory)/build/test/jitcatunittests/JitCatUnitTests'
      artifact: 'Build_GCC_UnitTests'
      displayName: 'Publish GCC Build of JitCatUnitTests'

- job: 'Test_GCC'
  displayName: 'Test release build of JitCat on Linux, built with GCC'
  dependsOn: 'Build_GCC'
  continueOnError: true
  steps:
    - checkout: none
    - task: DownloadPipelineArtifact@2
      inputs:
        artifact: 'Build_GCC_UnitTests'
        path: $(Build.SourcesDirectory)/bin
    - script: 'tree ..'
      displayName: 'Directory structure'
      failOnStderr: false
      enabled: true  
    - script: 'bin/JitCatUnitTests'
      displayName: 'Catch2 Unit Tests'
      failOnStderr: true
      enabled: true

