# For more information, see:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-18.04'

steps:
  - task: CMake@1
    displayName: 'CMake'
    inputs:
      cmakeArgs: '..'

  - task: CMake@1
    displayName: 'CMake'
    inputs:
      cmakeArgs: '--build . --config Release'

  - task: BatchScript@1
    displayName: 'Catch2 Unit Tests'
    inputs:
      filename: build/Release/test/jitcatunittests/JitCatUnitTests'
    continueOnError: true