# For more information, see:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-18.04'

jobs:
- job: 'Build_GCC'
  displayName: 'Release build of JitCat on Linux with GCC'
  steps:
    - task: CMake@1
      displayName: 'CMake'
      inputs:
        cmakeArgs: '..'

    - task: CMake@1
      displayName: 'CMake'
      inputs:
        cmakeArgs: '--build . --config Release -j2'
    - script: 'tree .'
      displayName: 'Directory structure'
      failOnStderr: false
      enabled: true  
    - publish: $(Build.SourcesDirectory)/build
      artifact: Build_GCC_Output
      displayName: 'Output of GCC Build'

- job: 'Test_GCC'
  displayName: 'Test release build of JitCat on Linux, built with GCC'
  dependsOn: 'Build_GCC'
  continueOnError: true
  steps:
    - checkout: none
    - download: current
      artifact: Build_GCC_Output
    - script: 'tree .'
      displayName: 'Directory structure'
      failOnStderr: false
      enabled: true  
    - script: 'build/test/jitcatunittests/JitCatUnitTests'
      displayName: 'Catch2 Unit Tests'
      failOnStderr: true
      enabled: true

