# For more information, see:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-18.04'

jobs:
- job: 'Build_GCC'
  displayName: 'Release build of JitCat on Linux with GCC'
  steps:
    - task: CMake@1
      displayName: 'CMake'
      inputs:
        cmakeArgs: '..'

    - task: CMake@1
      displayName: 'CMake'
      inputs:
        cmakeArgs: '--build . --config Release'

- job: 'Test_GCC'
  displayName: 'Test release build of JitCat on Linux, built with GCC'
  dependsOn: 'Build_GCC'
  continueOnError: true
  steps:
    - script: 'build/test/jitcatunittests/JitCatUnitTests'
      displayName: 'Catch2 Unit Tests'
      failOnStderr: true
      enabled: true

- job: 'DirectoryListing_GCC'
  displayName: 'Directory and file tree of output'
  dependsOn: 'Build_GCC'
  steps:
    - script: 'tree .'
      displayName: 'Directory structure'
      failOnStderr: false
      enabled: false

