# For more information, see:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-18.04'

steps:
  - task: CMake@1
    displayName: 'CMake'
    inputs:
      cmakeArgs: '..'

  - task: CMake@1
    displayName: 'CMake'
    inputs:
      cmakeArgs: '--build . --config Release'

  - script: 'build/Release/test/jitcatunittests/JitCatUnitTests'
    displayName: 'Catch2 Unit Tests'
    failOnStderr: true
    enabled: false

- script: 'tree -d ..'
    displayName: 'Directory structure'
    failOnStderr: false
    enabled: true

