/*
  This file is part of the JitCat library.
	
  Copyright (C) Machiel van Hooren 2018
  Distributed under the MIT License (license terms are at http://opensource.org/licenses/MIT).
*/

#pragma once

#include "jitcat/CatArgumentList.h"
#include "jitcat/CatAssignableExpression.h"
#include "jitcat/CatAssignmentOperator.h"
#include "jitcat/CatASTNode.h"
#include "jitcat/CatBuiltInFunctionCall.h"
#include "jitcat/CatClassDefinition.h"
#include "jitcat/CatConstruct.h"
#include "jitcat/CatDefinition.h"
#include "jitcat/CatDestruct.h"
#include "jitcat/CatErrorExpression.h"
#include "jitcat/CatForLoop.h"
#include "jitcat/CatFunctionDefinition.h"
#include "jitcat/CatFunctionOrConstructor.h"
#include "jitcat/CatFunctionParameterDefinitions.h"
#include "jitcat/CatIdentifier.h"
#include "jitcat/CatIfStatement.h"
#include "jitcat/CatIndirectionConversion.h"
#include "jitcat/CatInfixOperator.h"
#include "jitcat/CatInheritanceDefinition.h"
#include "jitcat/CatLinkNode.h"
#include "jitcat/CatLiteral.h"
#include "jitcat/CatMemberAccess.h"
#include "jitcat/CatMemberFunctionCall.h"
#include "jitcat/CatOperatorNew.h"
#include "jitcat/CatOwnershipSemanticsNode.h"
#include "jitcat/CatPrefixOperator.h"
#include "jitcat/CatRange.h"
#include "jitcat/CatReturnStatement.h"
#include "jitcat/CatScopeBlock.h"
#include "jitcat/CatScopeFunctionCall.h"
#include "jitcat/CatScopeRoot.h"
#include "jitcat/CatSourceFile.h"
#include "jitcat/CatStatement.h"
#include "jitcat/CatStaticFunctionCall.h"
#include "jitcat/CatStaticIdentifier.h"
#include "jitcat/CatStaticMemberAccess.h"
#include "jitcat/CatStaticScope.h"
#include "jitcat/CatTypedExpression.h"
#include "jitcat/CatTypeNode.h"
#include "jitcat/CatTypeOrIdentifier.h"
#include "jitcat/CatVariableDeclaration.h"
#include "jitcat/CatVariableDefinition.h"